Networkable/force-app/main/default/objects/Community_Network__c/Community_Network__c.object-meta.xml
<CustomObject>
    <label>Community Network</label>
    <nameField>
        <displayFormat>ONR-{000000000}</displayFormat>
        <label>Opportunity Network Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Networks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Networkable/force-app/main/default/objects/Community_Network__c/fields/Community_Account__c.field-meta.xml
<CustomField>
    <fullName>Community_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Community Networks (Community Account)</relationshipLabel>
    <relationshipName>Community_Networks1</relationshipName>
    <type>Lookup</type>
</CustomField>

Networkable/force-app/main/default/objects/Community_Network__c/fields/Community_Role__c.field-meta.xml
<CustomField>
    <fullName>Community_Role__c</fullName>
    <label>Community Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Networkable/force-app/main/default/objects/Community_Network__c/fields/End_Client__c.field-meta.xml
<CustomField>
    <fullName>End_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Community Networks (End Client)</relationshipLabel>
    <relationshipName>Community_Networks3</relationshipName>
    <type>Lookup</type>
</CustomField>

Networkable/force-app/main/default/objects/Community_Network__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Network Relation</relationshipLabel>
    <relationshipName>Community_Networks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Networkable/force-app/main/default/objects/Community_Network__c/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Community Networks</relationshipLabel>
    <relationshipName>Community_Networks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Networkable/force-app/main/default/objects/Community_Network__c/fields/Primary_Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account_Role__c</fullName>
    <label>Primary Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Project manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Networkable/force-app/main/default/objects/Community_Network__c/fields/Primary_Account_Role_Influence_Weight__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account_Role_Influence_Weight__c</fullName>
    <label>Primary Account Role Influence Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Networkable/force-app/main/default/objects/Community_Network__c/fields/Winning_Specifier__c.field-meta.xml
<CustomField>
    <fullName>Winning_Specifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Specifier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Community Networks (Winning Specifier)</relationshipLabel>
    <relationshipName>Community_Networks2</relationshipName>
    <type>Lookup</type>
</CustomField>

Networkable/force-app/main/default/objects/Opportunity/fields/End_Client__c.field-meta.xml
<CustomField>
    <fullName>End_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End Client)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

Networkable/force-app/main/default/objects/Opportunity/fields/Winning_Specifier__c.field-meta.xml
<CustomField>
    <fullName>Winning_Specifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Specifier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Winning Specifier)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

Networkable/force-app/main/default/objects/Roles_Managment__mdt/Roles_Managment__mdt.object-meta.xml
<CustomObject>
    <label>Roles Managment</label>
    <pluralLabel>Roles Managments</pluralLabel>
</CustomObject>

Networkable/force-app/main/default/objects/Roles_Managment__mdt/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Builder</fullName>
                <default>true</default>
                <label>Builder</label>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Project manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Networkable/force-app/main/default/objects/Roles_Managment__mdt/fields/Role_Influence_Weight__c.field-meta.xml
<CustomField>
    <fullName>Role_Influence_Weight__c</fullName>
    <label>Role Influence Weight</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Networkable/force-app/main/default/classes/CommunityNetworkTriggerHandler.cls
public with sharing class CommunityNetworkTriggerHandler extends TriggerHandler {

    List<Community_Network__c> triggerRecordsList = (List<Community_Network__c>) Trigger.new;
    List<Community_Network__c> triggerOldRecordList = (List<Community_Network__c>) Trigger.old;

    public void populateRecordFields() {
        List<Roles_Managment__mdt> roleManagmentList = Roles_Managment__mdt.getAll().values();
        Set<Id> oppIds = new Set<Id>();
        for (Community_Network__c comNet : triggerRecordsList) {
            oppIds.add(comNet.Opportunity__c);
        }
        List<Opportunity> oppList = [SELECT Id, Name, AccountId, End_Client__c, Winning_Specifier__c FROM Opportunity WHERE Id IN :oppIds];
        if (oppList.size() > 0) {
            for (Community_Network__c comNetRec : triggerRecordsList) {
                for (Opportunity opp : oppList) {
                    if (opp.Id == comNetRec.Opportunity__c) {
                        comNetRec.End_Client__c = opp.End_Client__c;
                        comNetRec.Winning_Specifier__c = opp.Winning_Specifier__c;
                    }
                }
                for (Roles_Managment__mdt mdt : roleManagmentList) {
                    if (mdt.Role__c == comNetRec.Primary_Account_Role__c) {
                        if (comNetRec.Primary_Account_Role_Influence_Weight__c == null) {
                            comNetRec.Primary_Account_Role_Influence_Weight__c = mdt.Role_Influence_Weight__c;
                        }
                    }
                }
            }
        }
    }

    public void makeCommunityNetworkRecordIsPrimary() {
        for (Community_Network__c comNet : triggerRecordsList) {
            if (comNet.Community_Account__c == null && comNet.Community_Role__c == null) {
                comNet.isPrimary__c = true;
            }
        }
    }

    public void updatePrimaryAccountsAfterCreateRecord() {
        Set<Id> accountIds = new Set<Id>();
        for (Community_Network__c comNet : triggerRecordsList) {
            accountIds.add(comNet.Primary_Account__c);
        }
        if (accountIds.size() > 0) {
            OpportunityTriggerHandler.updateAccountRollUpFields(accountIds);
        }
    }

    public void updatePrimaryAccountsAfterUpdateRecord() {
        Set<Id> accountIds = new Set<Id>();
        for (Community_Network__c comNet : triggerRecordsList) {
            if (
                (comNet.Opportunity__c != ((Community_Network__c)Trigger.oldMap.get(comNet.Id)).Opportunity__c) ||
                (comNet.Primary_Account__c != ((Community_Network__c)Trigger.oldMap.get(comNet.Id)).Primary_Account__c)
            ) {
                accountIds.add(comNet.Primary_Account__c);
            }
        }
        if (accountIds.size() > 0) {
            OpportunityTriggerHandler.updateAccountRollUpFields(accountIds);
        }
    }

    public void updatePrimaryAccountsAfterDeleteRecord() {
        Set<Id> accountIds = new Set<Id>();
        for (Community_Network__c comNet : triggerOldRecordList) {
            accountIds.add(comNet.Primary_Account__c);
        }
        if (accountIds.size() > 0) {
            OpportunityTriggerHandler.updateAccountRollUpFields(accountIds);
        }
    }

    public override void beforeInsert() {
        populateRecordFields();
        makeCommunityNetworkRecordIsPrimary();
    }

    public override void beforeUpdate() {
        populateRecordFields();
    }

    public override void afterInsert() {
        updatePrimaryAccountsAfterCreateRecord();
    }

    public override void afterUpdate() {
        updatePrimaryAccountsAfterUpdateRecord();
    }

    public override void afterDelete() {
        updatePrimaryAccountsAfterDeleteRecord();
    }

}